# Generated by Django 2.0.5 on 2018-05-27 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180527_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record created date', verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last updated date', verbose_name='Modified date')),
                ('body', models.TextField(verbose_name='Reply')),
                ('upvotes', models.PositiveIntegerField()),
                ('downvotes', models.PositiveIntegerField()),
                ('published', models.BooleanField(default=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='news.Comment')),
                ('user', models.ForeignKey(on_delete=models.SET(news.models.handle_deleted_user), related_name='replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['comment', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
