# Generated by Django 2.0.5 on 2018-05-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20180527_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='translation',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='translation',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
