# Generated by Django 2.0.5 on 2018-05-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20180527_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': ['-published_at'], 'ordering': ['-updated_at', '-status']},
        ),
        migrations.AddField(
            model_name='post',
            name='breaking',
            field=models.BooleanField(default=False),
        ),
    ]
