# Generated by Django 2.0.5 on 2018-05-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20180527_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='translation',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catagory',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='translation',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='tag',
            name='translation',
            field=models.CharField(max_length=60),
        ),
    ]
