# Generated by Django 2.0.5 on 2018-05-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20180527_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Record created date', null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last updated date', null=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Record created date', null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last updated date', null=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Record created date', null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last updated date', null=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Record created date', null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last updated date', null=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Record created date', null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last updated date', null=True, verbose_name='Modified date'),
        ),
    ]
