# Generated by Django 2.0.5 on 2018-05-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20180529_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
