# Generated by Django 2.0.5 on 2018-06-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_catagory_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='picture',
            field=models.ImageField(upload_to='catagory/pictures/'),
        ),
    ]
