# Generated by Django 2.0.5 on 2018-06-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20180602_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': ['-published_at'], 'ordering': ['-published_at', '-updated_at', '-status']},
        ),
    ]
