# Generated by Django 2.0.5 on 2018-06-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20180602_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='picture',
        ),
        migrations.AddField(
            model_name='catagory',
            name='thumbnail_lg',
            field=models.ImageField(blank=True, upload_to='catagory/thumbnails/'),
        ),
        migrations.AddField(
            model_name='catagory',
            name='thumbnail_md',
            field=models.ImageField(blank=True, upload_to='catagory/thumbnails/'),
        ),
        migrations.AddField(
            model_name='catagory',
            name='thumbnail_sm',
            field=models.ImageField(blank=True, upload_to='catagory/thumbnails/'),
        ),
    ]
