# Generated by Django 2.0.5 on 2018-06-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20180602_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture1',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_lg',
            field=models.ImageField(blank=True, upload_to='posts/thumbnails/'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_md',
            field=models.ImageField(blank=True, upload_to='posts/thumbnails/'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_sm',
            field=models.ImageField(blank=True, upload_to='posts/thumbnails/'),
        ),
    ]
