# Generated by Django 2.0.5 on 2018-06-02 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20180602_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
