# Generated by Django 2.0.5 on 2018-06-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_remove_post_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='thumbnail_lg',
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='thumbnail_md',
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='thumbnail_sm',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbnail_md',
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_sm',
            field=models.ImageField(blank=True, help_text='100x81 pixels thumbnail', upload_to='posts/thumbnails/'),
        ),
    ]
