# Generated by Django 2.0.5 on 2018-06-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_auto_20180602_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail_md',
            field=models.ImageField(blank=True, upload_to='posts/thumbnails/'),
        ),
    ]
