# Generated by Django 2.0.5 on 2018-06-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_post_thumbnail_md'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='thumbnail_lg',
            field=models.ImageField(blank=True, upload_to='catagory/thumbnails/'),
        ),
        migrations.AddField(
            model_name='catagory',
            name='thumbnail_md',
            field=models.ImageField(blank=True, upload_to='catagory/thumbnails/'),
        ),
        migrations.AddField(
            model_name='catagory',
            name='thumbnail_sm',
            field=models.ImageField(blank=True, help_text='100x81 pixels thumbnail', upload_to='catagory/thumbnails/'),
        ),
    ]
