# Generated by Django 2.0.5 on 2018-06-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_auto_20180602_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catagory',
            old_name='thumbnail_sm',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='thumbnail_lg',
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='thumbnail_md',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbnail_lg',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbnail_md',
        ),
        migrations.AddField(
            model_name='catagory',
            name='picture',
            field=models.ImageField(blank=True, upload_to='catagory/pictures/'),
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, upload_to='posts/pictures/'),
        ),
    ]
