# Generated by Django 2.0.5 on 2018-06-04 14:59

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0027_auto_20180603_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record created date', null=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last updated date', null=True, verbose_name='Modified date')),
                ('name', models.CharField(max_length=60)),
                ('competition_type', models.CharField(choices=[('LEAGUE', 'League'), ('PLAYOFF', 'Playoffs'), ('TOURNAMENT', 'Tournament'), ('FRIENDLY', 'Friendly')], max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logo/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['competition_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record created date', null=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last updated date', null=True, verbose_name='Modified date')),
                ('title', models.CharField(help_text='Title of the match', max_length=60, null=True)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, verbose_name='Short match summary')),
                ('match_status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('PLAYED', 'Played'), ('SUSPENDED', 'Suspended')], default='UPCOMING', max_length=10)),
                ('match_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=100)),
                ('first_team_score', models.PositiveIntegerField(blank=True, null=True)),
                ('second_team_score', models.PositiveIntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.Competition')),
            ],
            options={
                'ordering': ['is_featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record created date', null=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last updated date', null=True, verbose_name='Modified date')),
                ('team_type', models.CharField(choices=[('CLUB', 'Club'), ('NATIONAL', 'National Team'), ('EXHIBITION', 'Exhibition Team')], max_length=10)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('name', models.CharField(max_length=60)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('nickname', models.CharField(blank=True, max_length=60)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logo/')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['team_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='first_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='competitions.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='second_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='competitions.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='tags',
            field=models.ManyToManyField(related_name='matches', to='news.Tag'),
        ),
    ]
