# Generated by Django 2.0.5 on 2018-06-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='full_name',
        ),
        migrations.AddField(
            model_name='competition',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='translation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='translation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='translation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
