# Generated by Django 2.0.5 on 2018-06-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20180604_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['is_featured', 'title'], 'verbose_name_plural': 'Matches'},
        ),
    ]
